# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: amber123013.github.io
date_format: "ordinal"
title: amber
subtitle: "这只是第一步"
description: "amber的个人博客"
keywords: amber, 编程, android, amber123013.cn
favicon: /favicon.ico
timezone: Asia/Fuan
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 
organization: null,null.
organization_url: 
location: Sanming, China
email: amber123013@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: amber123013/amber123013.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: amber123013
twitter_username: amber123013

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: gitalk
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: null
disqus_username: null
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: amber123013
    repo: amber123013.github.io
    clientID: 26ab70d7c8ef4313be5f
    clientSecret: 3f1835280259a2b16b1860b185ec8fd3ec0f75f6
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Python]
